name: agent_env_new
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - flask>=2.3.0
  - python-docx>=1.1.0
  - numpy>=1.26.4
  - scikit-learn>=1.5.2
  - pyyaml>=6.0.1
  - pdfplumber>=0.11.0
  - scipy>=1.14.1
  - pyinstaller>=6.0.0
  - pip
  - pip:
      - openai>=1.0.0