name: Build Windows exe

on:
  push:
    branches: [ master ]  # change to [ main ] if your branch is main
  workflow_dispatch:        # manual trigger

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup virtual environment
      run: |
        python -m venv venv

    - name: Install dependencies
      run: |
        venv\Scripts\python.exe -m pip install --upgrade pip
        venv\Scripts\python.exe -m pip install flask pyyaml numpy scipy scikit-learn openai pdfplumber python-docx

    - name: Build executable with PyInstaller
      run: |
        venv\Scripts\python.exe -m pip show pyinstaller || venv\Scripts\python.exe -m pip install pyinstaller
        venv\Scripts\python.exe -m PyInstaller --noconfirm --onefile ` 
          --add-data=configs;configs `
          --add-data=resumes;resumes `
          --hidden-import=numpy.core._exceptions `
          --hidden-import=numpy.core._methods `
          --hidden-import=numpy.fft._pocketfft `
          --hidden-import=numpy.linalg._umath_linalg `
          --hidden-import=scipy._lib._ufuncs_cxx `
          --hidden-import=scipy.special._special_ufuncs `
          --hidden-import=yaml `
          --hidden-import=flask `
          --name=hr_agent_tbz_aws `
          hr_agent_tbz_aws.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hr_app-windows-exe
        path: dist/hr_agent_tbz_aws.exe
